### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Thane5** [BlenderKit/tabs_interface#2]
There is an error when i try to enable this addon in Blender 4.0.2. After installing the zip file, it does show up in the addon list but is not enabled by default. If i force enable it, this error appears:

```
Traceback (most recent call last):
  File "C:\Users\MyUsername\Programme\blender daily\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Users\MyUsername\Programme\blender daily\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\MyUsername\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\tabs_interface-main\__init__.py", line 26, in <module>
    from tabs_interface import panel_order
ModuleNotFoundError: No module named 'tabs_interface'
```

**Comment by jujpenabe** [comment]
Hi @Thane5!
After downloaded de zip file change the directory name to just "tabs_interface" removing the "-main" part of the name
![image](https://github.com/BlenderKit/tabs_interface/assets/17988529/6e88f12e-3781-4a9f-8fb2-501766fe4a9f)
-->
![image](https://github.com/BlenderKit/tabs_interface/assets/17988529/6a78d0e2-f9d2-4f4e-b743-c5a49cc2c308)

The reinstall the addon as usual in blender

**Comment by Thane5** [comment]
Ah, thanks. But I had to re-compress it to a zip file after renaming the folder. That's definitely a bit inconvenient.
